<a href="https://colab.research.google.com/github/slatej1/Everside/blob/main/Champlain_Capital468.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd


# Load the Excel file
file_path = 'Champlain Capital Partners IV LP Q1 2024 Form 468.pdf.xlsx'
xls = pd.ExcelFile(file_path)

# Initialize the dictionary with the same keys as your original script
data = {

    "Portfolio Company Name": [],
    "Employer ID": [],
    "Critical Technology": [],
    "Financing Type": [],
    "Investment Type": [],
    "Financing Description": [],
    "Initial Financing Date": [],
    "Equity Capital Investment": [],
    "Interest or Dividend Rate": [],
    "Ownership % (Fully Diluted)": [],
    "Restructured": [],
    "Loan / Debt Status": [],
    "Total Cash Invested (A)": [],
    "Cost at Beginning Period": [],
    "Loan": [],
    "Debt Equity": [],
    "Portfolio Securities Recievables from Sale of": [],
    "Assets Acquired": [],
    "Assets Acquired Operating Concerns Acquired": [],
    "Notes and Other Equity in Reinvestor/Relender": [],
    "Exception": [],
    "Totals": [],

}
def extract_value(df, header):
    for col in df.columns:
        if df[col].str.contains(header, na=False).any():
            value = df[df[col].str.contains(header, na=False)].iloc[0, df.columns.get_loc(col) + 1]
            return value
    return None

# Iterate through each sheet in the Excel file and populate the dictionary
for sheet_name in xls.sheet_names:
    df = pd.read_excel(xls, sheet_name)

    # Example: assuming the first row is the header and the rest are the values
    for column in df.columns:
        if column in data:
            data[column].extend(df[column].dropna().tolist())

# Print the populated dictionary
for key, value in data.items():
    print(f"{key}: {value}")

Portfolio Company Name: []
Employer ID: []
Critical Technology: []
Financing Type: []
Investment Type: []
Financing Description: []
Initial Financing Date: []
Equity Capital Investment: []
Interest or Dividend Rate: []
Ownership % (Fully Diluted): []
Restructured: []
Loan / Debt Status: []
Total Cash Invested (A): []
Cost at Beginning Period: []
Loan: []
Debt Equity: []
Portfolio Securities Recievables from Sale of: []
Assets Acquired: []
Assets Acquired Operating Concerns Acquired: []
Notes and Other Equity in Reinvestor/Relender: []
Exception: []
Totals: []

In [ ]:
df

,TOC,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104
0,"Table of Contents\n""Ctrl-t"" will take you back...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ONLY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Form Section,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Form / Page Order,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Recommended Entry Order,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Annual Submission,NaN,NaN,NaN,NaN,NaN,NaN,Quarterly Accrual/Reinv Leveraged ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Audited Tab Name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Cover,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1-Cover,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BalanceÂ Sheet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2&3-Bal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1195,28 Maximum Permissible Capital Impairment P...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1198,NAICS Search Tool. Copy NAICS 2022 Code and ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
start_row = 420
df = pd.read_excel(file_path, skiprows=start_row)
pd.options.display.max_columns = None
pd.options.display.max_rows = 10

In [ ]:
fte = df.loc[440, "Unnamed: 97"]
f_vet = df.loc[482, "Unnamed: 39"]
f_race = df.loc[482, "Unnamed: 48"]
f_gender= df.loc[482, "Unnamed: 58"]

c_vet = df.loc[482, "Unnamed: 77"]
c_race = df.loc[482, "Unnamed: 89"]
c_gender= df.loc[482, "Unnamed: 83"]

city = df.loc[517, "Unnamed: 12"]
state = df.loc[517, "Unnamed: 35" ]
portco = df.loc[482, "Unnamed: 39"]
revenue = df.loc[539, "Unnamed: 12"]
ttm_revenue= df.loc[539, "Unnamed: 35"]
ebitda = df.loc[541, "Unnamed: 12"]
ttm_ebitda = df.loc[541, "Unnamed: 35"]
tev = df.loc[538, "Unnamed: 57"]
ttm_tev = df.loc[538,"Ownership\n% (Fully Diluted)" ]
tev_multiple = df.loc[539, "Unnamed: 57"]
ttm_tev_multiple = df.loc[539, "Ownership\n% (Fully Diluted)"]
leverage = df.loc[540,"Unnamed: 57"]
ttm_leverage = df.loc[540,"Ownership\n% (Fully Diluted)" ]
leverage_multiple = df.loc[541,"Unnamed: 57"]
ttm_leverage_multiple = df.loc[541,"Ownership\n% (Fully Diluted)"]

df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
#df.head(1)

nan nan nan 4.9x 5.4x

In [ ]:
df

,Portfolio Company Name,Employer ID,Critical Technology (if applicable),Financing Type,Investment Type,Financing Description,Initial Financing Date,Equity Capital Investment,Interest or Dividend Rate,Ownership\n% (Fully Diluted),Restructur ed?,Loan/ Debt Status,Total Cash Invested (A),Cost at Beginning Period
0,Simplified E-Solutions,81-4872846,NaN,Loan,Senior Debt,NaN,2023-11-10 00:00:00,NaN,0.12,NaN,NaN,Performing,11618914,11618914.0
1,Simplified E-Solutions,81-4872846,NaN,Equity,Participation Interest (Equity),"12,591 Series A Preferred Units",2023-11-10 00:00:00,Y,0.08,NaN,NaN,NaN,12590631,12590631.0
2,Simplified E-Solutions,81-4872846,NaN,Equity,Participation Interest (Equity),"22,411 Common Units",2023-11-10 00:00:00,Y,NaN,0.28,NaN,NaN,280,280.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
775,28 Maximum Permissible Capital Impairment P...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
777,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
778,NAICS Search Tool. Copy NAICS 2022 Code and ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import numpy as np
def merge_rows(group):
    if group.empty:
        return pd.Series(dtype='float64')

    merged_row = group.iloc[0].copy()
    for col in group.columns:
        if col not in ['Financing Type']:
            merged_row[col] = group[col].dropna().iloc[0] if not group[col].dropna().empty else np.nan
    merged_row['Total Cash Invested (A)'] = group['Total Cash Invested (A)'].sum()
    merged_row['Cost at Beginning Period'] = group['Cost at Beginning Period'].sum()
    return merged_row

# Group by 'Financing Type' and apply the merging function
result = df.groupby('Financing Type').apply(merge_rows).reset_index(drop=True)

result = result.dropna(subset=['Portfolio Company Name'])

# Convert 'Interest or Dividend Rate' to percentages
result['Interest or Dividend Rate'] = result['Interest or Dividend Rate'].apply(lambda x: f"{x*100:.0f}%" if pd.notnull(x) else x)
result['Ownership\n% (Fully Diluted)'] = result['Ownership\n% (Fully Diluted)'].apply(lambda x: f"{x*100:.0f}%" if pd.notnull(x) and isinstance(x, (int, float)) else x)
# Format 'Total Cash Invested (A)' and 'Cost at Beginning Period' with dollar signs and commas
result['Total Cash Invested (A)'] = result['Total Cash Invested (A)'].apply(lambda x: f"${x:,.0f}" if pd.notnull(x) else x)
result['Cost at Beginning Period'] = result['Cost at Beginning Period'].apply(lambda x: f"${x:,.0f}" if pd.notnull(x) else x)

result = result.drop(result.index[0])

In [ ]:
start_row = 476
df_ext = pd.read_excel(file_path, skiprows=start_row)
df_ext = df_ext.loc[:, ~df_ext.columns.str.contains('^Unnamed')]

In [ ]:
row1 = df_ext.loc[1]
row2 = df_ext.loc[2]

summed_columns = ['Cost at End of Period', 'SBA Reported Value (B)', 'GAAP Reported Value (C)']
merged_row = row1[summed_columns] + row2[summed_columns]
merged_row = row1.combine_first(row2).copy()

for col in summed_columns:
    merged_row[col] = row1[col] + row2[col]

df_ext.loc[1.5] = merged_row

# Sort the DataFrame and reset the index
df_ext = df_ext.sort_index().reset_index(drop=True)

# Drop the original rows
#df_ext = df_ext.drop([2, 4]).reset_index(drop=True)

In [ ]:
df_ext = df_ext.drop([1,3], axis=0)

In [ ]:
x  = df.join(df_ext)

In [ ]:
row2 = x.loc[1]
row3 = x.loc[2]
merged_row = row2.combine_first(row3)
x.loc[1] = merged_row
x = x.drop(2).reset_index(drop=True)

In [ ]:
x['Interest or Dividend Rate'] = pd.to_numeric(x['Interest or Dividend Rate'], errors='coerce')
x['Ownership\n% (Fully Diluted)'] = pd.to_numeric(x['Ownership\n% (Fully Diluted)'], errors='coerce')

# Applying the percentage format
x['Interest or Dividend Rate'] = x['Interest or Dividend Rate'].apply(lambda x: f"{x*100:.0f}%" if pd.notnull(x) else x)
x['Ownership\n% (Fully Diluted)'] = x['Ownership\n% (Fully Diluted)'].apply(lambda x: f"{x*100:.0f}%" if pd.notnull(x) else x)

In [ ]:
required_cols = ['Portfolio Company Name', 'Employer ID',
       'Critical Technology (if applicable)', 'Financing Type',
       'Type of Equity Security','Type of Debt Security', 'Financing Description', 'Date of Investment',
       'Invested Dollars - Debt Cost', "Invested Dollars - Debt Realized Value", "Invested Dollars - Debt FMV", "Invested Dollars - Equity Cost",
        "Invested Dollars - Equity Realized Value", "Invested Dollars - Equity FMV",'Equity Capital Investment', 'Interest or Dividend Rate',
       'Restructur ed?', 'Loan/ Debt Status',
       'Total Cash Invested (A)', 'Cost at Beginning Period',
       'Schedule 1C\nReference Number', 'Addition/ Deduction',
       'Non-Cash Gain included in Cost at End of Period',
       'Cost at End of Period', 'Unrealized Appreciation',
       '(Unrealized Depreciation)', "Equity Pricing - Equity Ownership (FD)",
       'Class 2 Date of Up Round', 'Current - Liquidity (Cash + Available Liquidity)',
       'Current SBA\nMult', 'Prior SBA\nMult', 'Current GAAP\nMult',
       'Prior GAAP\nMult', 'Debt Pricing - Total Coupon','Full Time Employees','Founder Veteran','Founder Race','Founder Gender','CEO Veteran','CEO Race','CEO Gender','City',
"State", "Revenue","TTM Revenue", "EBITDA", "TTM EBITDA", "TEV", "TTM TEV", "TEV Multiple", "TTM TEV Multiple", "Leverage", "TTM Leverage","Leverage Multiple", "TTM Leverage Multiple"]

In [ ]:
pd.options.display.max_columns = None
pd.options.display.max_rows = 15

In [ ]:
x.head()

,Portfolio Company Name,Employer ID,Critical Technology (if applicable),Financing Type,Investment Type,Financing Description,Initial Financing Date,Equity Capital Investment,Interest or Dividend Rate,Ownership\n% (Fully Diluted),Restructur ed?,Loan/ Debt Status,Total Cash Invested (A),Cost at Beginning Period,Schedule 1C\nReference Number,Addition/ Deduction,Non-Cash Gain included in Cost at End of Period,Cost at End of Period,Unrealized Appreciation,(Unrealized Depreciation),Class 1,Class 2,Class 2 Date of Up Round,SBA Reported Value (B),GAAP Reported Value (C),Cum. Cash Proceeds (D),Current SBA\nMult,Prior SBA\nMult,Current GAAP\nMult,Prior GAAP\nMult,First Investment Date
0,Simplified E-Solutions,81-4872846,NaN,Loan,Senior Debt,NaN,2023-11-10 00:00:00,NaN,12%,NaN,NaN,Performing,11618914,11618914.0,NaN,$ -,NaN,11618914,NaN,NaN,NaN,NaN,NaN,11618914,11618914,193648,1.0,NaN,1.0,NaN,2023-11-10
1,Simplified E-Solutions,81-4872846,NaN,Equity,Participation Interest (Equity),"12,591 Series A Preferred Units",2023-11-10 00:00:00,Y,8%,28%,NaN,NaN,12590631,12590631.0,NaN,-,NaN,12590911,NaN,NaN,NaN,NaN,NaN,12590911,12590911,139896,1.0,NaN,1.0,NaN,2023-11-10
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,-,NaN,NaN,NaN,NaN,NaN,-,-,NaN,NaN,NaN,NaN,NaN,NaT
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,-,NaN,NaN,NaN,NaN,NaN,-,-,NaN,NaN,NaN,NaN,NaN,NaT

In [ ]:
new = [col for col in required_cols if col not in x.columns]
final = pd.DataFrame(columns = new)
final  = final.join(x)
final

Empty DataFrame
Columns: [Type of Equity Security, Type of Debt Security, Date of Investment, Invested Dollars - Debt Cost, Invested Dollars - Debt Realized Value, Invested Dollars - Debt FMV, Invested Dollars - Equity Cost, Invested Dollars - Equity Realized Value, Invested Dollars - Equity FMV, Equity Pricing - Equity Ownership (FD), Current - Liquidity (Cash + Available Liquidity), Debt Pricing - Total Coupon, Full Time Employees, Founder Veteran, Founder Race, Founder Gender, CEO Veteran, CEO Race, CEO Gender, City, State, Revenue, TTM Revenue, EBITDA, TTM EBITDA, TEV, TTM TEV, TEV Multiple, TTM TEV Multiple, Leverage, TTM Leverage, Leverage Multiple, TTM Leverage Multiple, Portfolio Company Name, Employer ID, Critical Technology (if applicable), Financing Type, Investment Type, Financing Description, Initial Financing Date, Equity Capital Investment, Interest or Dividend Rate, Ownership
% (Fully Diluted), Restructur ed?, Loan/ Debt Status, Total Cash Invested (A), Cost at Beginning Period, Schedule 1C
Reference Number, Addition/ Deduction, Non-Cash Gain included in Cost at End of Period, Cost at End of Period, Unrealized Appreciation, (Unrealized Depreciation), Class 1, Class 2, Class 2 Date of Up Round, SBA Reported Value (B), GAAP Reported Value (C), Cum. Cash Proceeds (D), Current SBA
Mult, Prior SBA
Mult, Current GAAP
Mult, Prior GAAP
Mult, First Investment Date]
Index: []

In [ ]:
final_columns = list(set(required_cols) | set(x.columns))
final = pd.DataFrame(columns=final_columns)

# Copying the data from x to final for the common columns
common_columns = list(set(x.columns) & set(final.columns))
final[common_columns] = x[common_columns]
final

,Revenue,Employer ID,Type of Debt Security,Cum. Cash Proceeds (D),Current - Liquidity (Cash + Available Liquidity),Cost at End of Period,Total Cash Invested (A),Class 2 Date of Up Round,Interest or Dividend Rate,EBITDA,Addition/ Deduction,Invested Dollars - Equity Realized Value,GAAP Reported Value (C),Invested Dollars - Equity FMV,TTM Leverage Multiple,Financing Type,Ownership\n% (Fully Diluted),Equity Capital Investment,Equity Pricing - Equity Ownership (FD),TTM Revenue,Current SBA\nMult,Leverage,Prior GAAP\nMult,Schedule 1C\nReference Number,Investment Type,SBA Reported Value (B),Portfolio Company Name,Date of Investment,Full Time Employees,Critical Technology (if applicable),Restructur ed?,Type of Equity Security,Financing Description,TTM TEV,TEV Multiple,TEV,Class 1,Founder Gender,CEO Gender,Invested Dollars - Debt Cost,Initial Financing Date,Founder Race,CEO Veteran,Non-Cash Gain included in Cost at End of Period,Unrealized Appreciation,TTM Leverage,Class 2,Founder Veteran,Leverage Multiple,Loan/ Debt Status,Invested Dollars - Debt Realized Value,TTM EBITDA,State,Debt Pricing - Total Coupon,Invested Dollars - Debt FMV,(Unrealized Depreciation),Prior SBA\nMult,Cost at Beginning Period,Invested Dollars - Equity Cost,CEO Race,TTM TEV Multiple,Current GAAP\nMult,City,First Investment Date
0,NaN,81-4872846,NaN,193648,NaN,11618914,11618914,NaN,12%,NaN,$ -,NaN,11618914,NaN,NaN,Loan,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,Senior Debt,11618914,Simplified E-Solutions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-11-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Performing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11618914.0,NaN,NaN,NaN,1.0,NaN,2023-11-10
1,NaN,81-4872846,NaN,139896,NaN,12590911,12590631,NaN,8%,NaN,-,NaN,12590911,NaN,NaN,Equity,28%,Y,NaN,NaN,1.0,NaN,NaN,NaN,Participation Interest (Equity),12590911,Simplified E-Solutions,NaN,NaN,NaN,NaN,NaN,"12,591 Series A Preferred Units",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-11-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12590631.0,NaN,NaN,NaN,1.0,NaN,2023-11-10
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,-,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
4,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,-,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28 Maximum Permissible Capital Impairment P...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
775,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
777,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NAICS Search Tool. Copy NAICS 2022 Code and ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT

In [ ]:
if len(x) != len(final):
    # Assuming both DataFrames should have the same indices
    common_indices = final.index.intersection(x.index)
    final = final.loc[common_indices]
    x = x.loc[common_indices]

In [ ]:
final['Portfolio Company Name'] = x['Portfolio Company Name']
final['Employer ID'] = x['Employer ID']
final["Date of Investment"] = x["First Investment Date"]
final["Loan/ Debt Status"] = x["Loan/ Debt Status"]
final["Invested Dollars - Debt Cost"] = np.where(
    x['Financing Type'].isin(['Loan', 'Debt']),
    x['SBA Reported Value (B)'],
    np.nan)  # or 0, or any placeholder value you want to use

final["Invested Dollars - Debt Realized Value"] = np.where(
    x['Financing Type'].isin(['Loan', 'Debt']),
    x['GAAP Reported Value (C)'],
    np.nan)  # or 0, or any placeholder value you want to use

final["Invested Dollars - Debt FMV"] = np.where(
    x['Financing Type'].isin(['Loan', 'Debt']),
    x['GAAP Reported Value (C)'],
    np.nan)

final["Invested Dollars - Equity Cost"] = np.where(
    x['Financing Type'].isin(['Equity']),
    x['SBA Reported Value (B)'],
    np.nan)

final["Invested Dollars - Equity Realized Value"] = np.where(
    x['Financing Type'].isin(['Equity']),
    x['GAAP Reported Value (C)'],
    np.nan)

final["Invested Dollars - Equity FMV"] = np.where(
    x['Financing Type'].isin(['Equity']),
    x['GAAP Reported Value (C)'],
    np.nan)

final["Type of Equity Security"] = np.where(
    x['Financing Type'].isin(['Equity']),
    x['Financing Description'],
    np.nan)

final["Type of Debt Security"] = np.where(
    x['Financing Type'].isin(['Loan', 'Debt']),
    x['Investment Type'],
    np.nan)

final["Current - Liquidity (Cash + Available Liquidity)"] = x['Cum. Cash Proceeds (D)']
final["Debt Pricing - Total Coupon"] = np.where(
    x['Financing Type'].isin(['Loan', 'Debt']),
    x['Interest or Dividend Rate'],
    np.nan)
final["Equity Pricing - Equity Ownership (FD)"] = np.where(
    x['Financing Type'].isin(['Equity']),
    x['Ownership\n% (Fully Diluted)'],
    np.nan)
final["Equity Pricing - PIK"] = np.where(
    x['Financing Type'].isin(['Equity']),
    x['Interest or Dividend Rate'],
    np.nan)



final['Founder Veteran']=f_vet
final['Founder Race'] = f_race
final['Founder Gender'] = f_gender

final['CEO Veteran'] = c_vet
final['CEO Race'] = c_race
final['CEO Gender'] = c_gender
final['City'] = city
final["State"] = state

final["Revenue"] = revenue
final["TTM Revenue"] = ttm_revenue
final["EBITDA"] = ebitda
final["TTM EBITDA"] = ttm_ebitda
final["TEV"]=tev
final["TTM TEV"]=ttm_tev
final["TEV Multiple"]=tev_multiple
final["TTM TEV Multiple"] = ttm_tev_multiple
final["Leverage"] = leverage
final["TTM Leverage"] = ttm_leverage
final["Leverage Multiple"] = leverage_multiple
final["TTM Leverage Multiple"] = ttm_leverage_multiple

In [ ]:
final

,Revenue,Employer ID,Type of Debt Security,Cum. Cash Proceeds (D),Current - Liquidity (Cash + Available Liquidity),Cost at End of Period,Total Cash Invested (A),Class 2 Date of Up Round,Interest or Dividend Rate,EBITDA,Addition/ Deduction,Invested Dollars - Equity Realized Value,GAAP Reported Value (C),Invested Dollars - Equity FMV,TTM Leverage Multiple,Financing Type,Ownership\n% (Fully Diluted),Equity Capital Investment,Equity Ownership (FD),TTM Revenue,Current SBA\nMult,Leverage,Prior GAAP\nMult,Schedule 1C\nReference Number,Investment Type,SBA Reported Value (B),Portfolio Company Name,Date of Investment,Full Time Employees,Critical Technology (if applicable),Restructur ed?,Type of Equity Security,Financing Description,TTM TEV,TEV Multiple,TEV,Class 1,Founder Gender,CEO Gender,Invested Dollars - Debt Cost,Initial Financing Date,Founder Race,CEO Veteran,Non-Cash Gain included in Cost at End of Period,Unrealized Appreciation,TTM Leverage,Class 2,Founder Veteran,Leverage Multiple,Loan/ Debt Status,Invested Dollars - Debt Realized Value,TTM EBITDA,State,Debt Pricing - Total Coupon,Invested Dollars - Debt FMV,(Unrealized Depreciation),Prior SBA\nMult,Cost at Beginning Period,Invested Dollars - Equity Cost,CEO Race,TTM TEV Multiple,Current GAAP\nMult,City,First Investment Date,Equity Pricing - PIK,# of Full time Employees
0,18500000,81-4872846,Senior Debt,193648,193648,11618914,11618914,NaN,12%,8500000,$ -,NaN,11618914,NaN,5.4x,Loan,NaN,NaN,NaN,17754000,1.0,41475000,NaN,NaN,Senior Debt,11618914,Simplified E-Solutions,2023-11-10,NaN,NaN,NaN,NaN,NaN,50948000,9.4x,80000000,NaN,NaN,NaN,11618914,2023-11-10 00:00:00,NaN,NaN,NaN,NaN,41475000,NaN,NaN,4.9x,Performing,11618914,7707000,MO,12%,11618914,NaN,NaN,11618914.0,NaN,NaN,6.6x,1.0,Hazelwood,2023-11-10,NaN,16
1,18500000,81-4872846,NaN,139896,139896,12590911,12590631,NaN,8%,8500000,-,12590911,12590911,12590911,5.4x,Equity,28%,Y,28%,17754000,1.0,41475000,NaN,NaN,Participation Interest (Equity),12590911,Simplified E-Solutions,2023-11-10,NaN,NaN,NaN,Preferred,"12,591 Series A Preferred Units",50948000,9.4x,80000000,NaN,NaN,NaN,NaN,2023-11-10 00:00:00,NaN,NaN,NaN,NaN,41475000,NaN,NaN,4.9x,NaN,NaN,7707000,MO,NaN,NaN,NaN,NaN,12590631.0,12590911,NaN,6.6x,1.0,Hazelwood,2023-11-10,8%,16

In [ ]:
def standardize_equity_type(value):
    if isinstance(value, str):  # Check if the value is a string
        if 'common' in value.lower():
            return 'Common'
        elif 'preferred' in value.lower():
            return 'Preferred'
    return value

# Apply the function to the column
final['Type of Equity Security'] = final['Type of Equity Security'].apply(standardize_equity_type)
final.rename(columns={'Equity Pricing - Equity Ownership (FD)': ' Equity Ownership (FD)'}, inplace=True)
final["# of Full time Employees"]=fte
final = final.head(2)

In [ ]:
cols_to_add =["Cost at Beginning Period","SBA Reported Value (B)","GAAP Reported Value (C)","Total Cash Invested (A)","Cost at End of Period", "Current - Liquidity (Cash + Available Liquidity)", "Cum. Cash Proceeds (D)"  ]

sum_values = final[cols_to_add].sum()

# Creating a new row with the summed values
new_row = pd.DataFrame(sum_values).T

# Adding missing columns to new_row to match final dataframe
for col in final.columns:
    if col not in new_row.columns:
        new_row[col] = None

# Concatenating the new row with the final dataframe
final = pd.concat([final, new_row], ignore_index=True)
final

,Revenue,Employer ID,Type of Debt Security,Cum. Cash Proceeds (D),Current - Liquidity (Cash + Available Liquidity),Cost at End of Period,Total Cash Invested (A),Class 2 Date of Up Round,Interest or Dividend Rate,EBITDA,Addition/ Deduction,Invested Dollars - Equity Realized Value,GAAP Reported Value (C),Invested Dollars - Equity FMV,TTM Leverage Multiple,Financing Type,Ownership\n% (Fully Diluted),Equity Capital Investment,Equity Ownership (FD),TTM Revenue,Current SBA\nMult,Leverage,Prior GAAP\nMult,Schedule 1C\nReference Number,Investment Type,SBA Reported Value (B),Portfolio Company Name,Date of Investment,Full Time Employees,Critical Technology (if applicable),Restructur ed?,Type of Equity Security,Financing Description,TTM TEV,TEV Multiple,TEV,Class 1,Founder Gender,CEO Gender,Invested Dollars - Debt Cost,Initial Financing Date,Founder Race,CEO Veteran,Non-Cash Gain included in Cost at End of Period,Unrealized Appreciation,TTM Leverage,Class 2,Founder Veteran,Leverage Multiple,Loan/ Debt Status,Invested Dollars - Debt Realized Value,TTM EBITDA,State,Debt Pricing - Total Coupon,Invested Dollars - Debt FMV,(Unrealized Depreciation),Prior SBA\nMult,Cost at Beginning Period,Invested Dollars - Equity Cost,CEO Race,TTM TEV Multiple,Current GAAP\nMult,City,First Investment Date,Equity Pricing - PIK,# of Full time Employees
0,18500000,81-4872846,Senior Debt,193648,193648,11618914,11618914,NaN,12%,8500000,$ -,NaN,11618914,NaN,5.4x,Loan,NaN,NaN,NaN,17754000,1.0,41475000,NaN,NaN,Senior Debt,11618914,Simplified E-Solutions,2023-11-10,NaN,NaN,NaN,NaN,NaN,50948000,9.4x,80000000,NaN,NaN,NaN,11618914,2023-11-10 00:00:00,NaN,NaN,NaN,NaN,41475000,NaN,NaN,4.9x,Performing,11618914,7707000,MO,12%,11618914,NaN,NaN,11618914.0,NaN,NaN,6.6x,1.0,Hazelwood,2023-11-10,NaN,16
1,18500000,81-4872846,NaN,139896,139896,12590911,12590631,NaN,8%,8500000,-,12590911,12590911,12590911,5.4x,Equity,28%,Y,28%,17754000,1.0,41475000,NaN,NaN,Participation Interest (Equity),12590911,Simplified E-Solutions,2023-11-10,NaN,NaN,NaN,Preferred,"12,591 Series A Preferred Units",50948000,9.4x,80000000,NaN,NaN,NaN,NaN,2023-11-10 00:00:00,NaN,NaN,NaN,NaN,41475000,NaN,NaN,4.9x,NaN,NaN,7707000,MO,NaN,NaN,NaN,NaN,12590631.0,12590911,NaN,6.6x,1.0,Hazelwood,2023-11-10,8%,16
2,None,None,None,333544,333544,24209825,24209545,NaN,None,None,None,None,24209825,None,None,None,None,None,None,None,NaN,None,NaN,NaN,None,24209825,None,NaT,NaN,NaN,NaN,None,None,None,None,None,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,None,None,None,None,None,None,None,NaN,NaN,24209545.0,None,NaN,None,NaN,None,NaT,None,None
3,None,None,None,667088,667088,48419650,48419090,None,None,None,None,None,48419650,None,None,None,None,None,None,None,NaN,None,None,None,None,48419650,None,NaT,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,48419090.0,None,None,None,NaN,None,NaT,None,None

In [ ]:
new_row = {}

for col in final.columns:
    if col in ['Financing Type', 'Investment Type']:
        new_row[col] = 'Merged'
    elif final.loc[0, col] == final.loc[1, col]:
        new_row[col] = final.loc[0, col]
    elif pd.isna(final.loc[0, col]) and not pd.isna(final.loc[1, col]):
        new_row[col] = final.loc[1, col]
    elif pd.isna(final.loc[1, col]) and not pd.isna(final.loc[0, col]):
        new_row[col] = final.loc[0, col]
    else:
        new_row[col] = final.loc[0, col] if col not in cols_to_add else final.loc[0, col] + final.loc[1, col]

new_row = pd.DataFrame(new_row, index=[2])

# Inserting the new row into the dataframe
final = pd.concat([final.iloc[:2], new_row, final.iloc[2:]]).reset_index(drop=True)
final.iloc[[2]]

,Revenue,Employer ID,Type of Debt Security,Cum. Cash Proceeds (D),Current - Liquidity (Cash + Available Liquidity),Cost at End of Period,Total Cash Invested (A),Class 2 Date of Up Round,Interest or Dividend Rate,EBITDA,Addition/ Deduction,Invested Dollars - Equity Realized Value,GAAP Reported Value (C),Invested Dollars - Equity FMV,TTM Leverage Multiple,Financing Type,Ownership\n% (Fully Diluted),Equity Capital Investment,Equity Ownership (FD),TTM Revenue,Current SBA\nMult,Leverage,Prior GAAP\nMult,Schedule 1C\nReference Number,Investment Type,SBA Reported Value (B),Portfolio Company Name,Date of Investment,Full Time Employees,Critical Technology (if applicable),Restructur ed?,Type of Equity Security,Financing Description,TTM TEV,TEV Multiple,TEV,Class 1,Founder Gender,CEO Gender,Invested Dollars - Debt Cost,Initial Financing Date,Founder Race,CEO Veteran,Non-Cash Gain included in Cost at End of Period,Unrealized Appreciation,TTM Leverage,Class 2,Founder Veteran,Leverage Multiple,Loan/ Debt Status,Invested Dollars - Debt Realized Value,TTM EBITDA,State,Debt Pricing - Total Coupon,Invested Dollars - Debt FMV,(Unrealized Depreciation),Prior SBA\nMult,Cost at Beginning Period,Invested Dollars - Equity Cost,CEO Race,TTM TEV Multiple,Current GAAP\nMult,City,First Investment Date,Equity Pricing - PIK,# of Full time Employees
3,18500000,81-4872846,Senior Debt,333544,333544,24209825,24209545,NaN,12%,8500000,$ -,12590911,24209825,12590911,5.4x,Merged,28%,Y,28%,17754000,1.0,41475000,NaN,NaN,Merged,24209825,Simplified E-Solutions,2023-11-10,NaN,NaN,NaN,Preferred,"12,591 Series A Preferred Units",50948000,9.4x,80000000,NaN,NaN,NaN,11618914,2023-11-10 00:00:00,NaN,NaN,NaN,NaN,41475000,NaN,NaN,4.9x,Performing,11618914,7707000,MO,12%,11618914,NaN,NaN,24209545.0,12590911,NaN,6.6x,1.0,Hazelwood,2023-11-10,8%,16

In [ ]:
file_path = 'sample fund reporting tab.xlsx'
excel_df = pd.read_excel(file_path)

# Get the third row of the final DataFrame
third_row = final.iloc[2]

# Iterate over the columns in the Excel file and update with values from third_row_df
for col in excel_df.columns:
    if col in final.columns:
        excel_df.at[3, col] = third_row[col]

# Save the updated Excel file
updated_file_path = 'updated_fund_reporting.xlsx'
excel_df.to_excel(updated_file_path, index=False)

Index(['Portfolio Company Name', 'Date of Investment', 'Industry', 'Geography',
       'Use of Proceeds', 'Sponsor Name', 'Sponsor Type',
       'Name of Senior Lender', 'Type of Debt Security ',
       'Type of Equity Security', 'Intentionally Left Bank',
       'Intentionally Left Bank2', 'Intentionally Left Bank3',
       'Intentionally Left Bank4', 'Invested Dollars - Debt Cost',
       'Invested Dollars - Debt Realized Value', 'Invested Dollars - Debt FMV',
       'Invested Dollars - Equity Cost',
       'Invested Dollars - Equity Realized Value',
       'Invested Dollars - Equity FMV', 'Debt Pricing - Cash',
       'Debt Pricing - PIK', 'Debt Pricing - Total Coupon',
       'Debt Pricing - Maturity', 'Equity Pricing - Cash',
       'Equity Pricing - PIK', 'Equity Pricing - Equity Ownership (FD)',
       'At Close - Senior Debt', 'At Close - Sr. Debt Turns',
       'At Close - Total Debt', 'At Close - Total Debt Turns',
       'At Close - Liquidity (Cash + Available Liquidity)',
       'At Close - FCCR (Covenants)', 'At Close - Enterprise Value',
       'At Close - EV Multiple', 'At Close - Sales', 'At Close - EBITDA',
       'At Close - Capex', 'At Close - Column3', 'Current - Senior Debt',
       'Current - Sr. Debt Turns', 'Current - Total Debt',
       'Current - Total Debt Turns',
       'Current - Liquidity (Cash + Available Liquidity)',
       'Current - FCCR (Current -)', 'Current - Enterprise Value',
       'Current - EV Multiple', 'Current - Sales', 'Current - EBITDA',
       'Current - Capex', 'Current - EBITDA - Capex',
       'Status Compliance of Credit - Current Status',
       'Status Compliance of Credit - Type of Debt',
       'Status Compliance of Credit - Covenants Breach',
       'Status Compliance of Credit - Current on Interest',
       'Status Compliance of Credit - Date Interest Off',
       'Status Compliance of Credit - Days w/o Interest', 'Net Income: <$2M',
       'Tangible Net Worth: <$6M', 'At Close', 'Recent FYE',
       '("Green", Healthcare, Education, job training, etc) Y/N',
       'Company Address', 'Low/Mod Income', 'Hub Zone', 'Opportunity Zone',
       'Rural', 'Minority Owned ', 'Minority Owned %', 'Woman Owned',
       'Woman Owned %', 'Veteran Owned', 'Veterans Owned %',
       'Woman Management', 'Minority Management', 'Veteran Management',
       'Family Owned', 'Non - Committed Fund Sponsor',
       'Short, one sentence description of impact related comment',
       'Exit Date', 'Exit Multiple', 'Exit Leverage', 'Exit Returns Net IRR',
       'Exit Returns Net MOIC', 'Exit Scale', 'Exit Type', 'Exit Buyer'],
      dtype='object')

csv_file_path = "Champlain_Partners_468.csv"
final.to_csv(csv_file_path, index=False)

In [ ]:
common_columns = list(set(x.columns) & set(final.columns))
final[common_columns] = x[common_columns]

In [ ]:
final = pd.DataFrame(columns=required_cols)

# Adding missing columns from x to final
for col in x.columns:
    if col not in final.columns:
        final[col] = None

# Appending data from x to final
final = pd.concat([final, x], ignore_index=True)